name: Compile and Deploy PDF and PNGs

on:
  push:
    branches: main
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0

      - name: Build PDF 
        run: pixi run build

      - name: Optimize PNGs
        run: pixi run compress

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            term-card.pdf
            term-card-1.png
            term-card-2.png
          body: ${{ github.event.head_commit.message }}
          make_latest: ${{ github.ref_name == 'main' }}
